import json
import difflib
import sys
import tempfile
import unittest
from pathlib import Path

from storymem_agentic.cli import main
from storymem_agentic.alignment import analyze_whisperx_alignment
from storymem_agentic.agents import MockAgentBackend
from storymem_agentic.feedback import apply_revision_plan, build_revision_plan
from storymem_agentic.media_evaluator import evaluate_iteration
from storymem_agentic.planner import PlanCriticAgent, PromptPlannerAgent, build_production_plan, build_visual_bible, validate_plan_semantics
from storymem_agentic.orchestrator import default_storymem_dir, run_workflow
from storymem_agentic.review_agents import _normalize_model_report
from storymem_agentic.schemas import EvaluationReport, NurseryRhymeInput, ReviewerReport, RevisionPlan
from storymem_agentic.story_writer import story_from_plan, storymem_script_from_plan


class AgenticArchitectureTests(unittest.TestCase):
    def _structured_decision(self, lyrics=None, *, scene_suffix="", character_label="guide"):
        lyrics = lyrics or ["Line one from model", "Line two from model"]
        scenes = []
        for index, line in enumerate(lyrics, start=1):
            scenes.append(
                {
                    "scene_num": index,
                    "lyric_line": line,
                    "scene_goal": f"communicate lyric {index}{scene_suffix}",
                    "lyric_interpretation": f"planner interpretation for {line}{scene_suffix}",
                    "setting": f"a distinct full-frame storybook location {index} with foreground props and background depth{scene_suffix}",
                    "subjects": f"same rounded {character_label} with a soft scarf and friendly face",
                    "action": f"moves gently through beat {index} with clear child-safe expression{scene_suffix}",
                    "camera": f"Camera makes a slow planned move {index}",
                    "style": "soft pastel 3D animation, warm lighting, rounded uncluttered shapes",
                    "safety_adaptation": "no generated text, no dialogue, no inset frame, no scary imagery",
                    "selected_characters": [
                        {"label": character_label, "selection_rationale": f"fits lyric {index}"}
                    ],
                    "expected_mood": "calm bedtime mood",
                    "boundary_behavior": "fade" if index == len(lyrics) else "hold",
                    "cut": True,
                    "review_status": "pending",
                }
            )
        return {
            "lyrics": lyrics,
            "clip_count": len(lyrics),
            "target_duration_seconds": len(lyrics) * 5,
            "visual_bible": {
                "primary_world": "agent designed test world",
                "allowed_locations": [scene["setting"] for scene in scenes],
            },
            "selected_characters": [
                {
                    "label": character_label,
                    "description": f"same rounded {character_label} with a soft scarf and friendly face",
                    "selection_rationale": "chosen by planner fixture",
                    "continuity_constraints": ["same scarf"],
                    "negative_constraints": ["no text"],
                }
            ],
            "scenes": scenes,
            "music_prompt": "quiet celesta lullaby generated by backend",
        }

    def _plan(self):
        return build_production_plan(
            NurseryRhymeInput(
                rhyme_text="Twinkle, twinkle, little star,\nHow I wonder what you are!\nUp above the world so high,\n",
                target_duration_seconds=12,
                clip_count=3,
                seed=7,
            )
        )

    def test_planner_quantizes_segments_and_keeps_character_bank_out_of_prompts(self):
        plan = self._plan()
        self.assertEqual(plan.clip_count, 3)
        self.assertEqual(len(plan.character_bank), 3)
        for segment in plan.lyric_segments:
            self.assertAlmostEqual(segment.start_seconds * 24, round(segment.start_seconds * 24), places=5)
            self.assertAlmostEqual(segment.end_seconds * 24, round(segment.end_seconds * 24), places=5)
        self.assertLess(len(plan.scenes[0].video_prompt), 900)
        self.assertIn("toddler-safe lullaby animation", plan.scenes[0].video_prompt)
        self.assertIn("StoryMem keyframe memory", plan.scenes[0].video_prompt)
        self.assertIn("this prompt controls the new scene layout", plan.scenes[0].video_prompt)
        self.assertIn("no picture-in-picture", plan.scenes[0].video_prompt)
        self.assertNotIn("pajama_child", plan.scenes[0].video_prompt)
        self.assertNotIn("smiling_star", plan.scenes[0].video_prompt)

    def test_visual_prompts_do_not_embed_literal_lyrics(self):
        plan = self._plan()

        self.assertEqual(plan.scenes[0].subtitle_text, "Twinkle, twinkle, little star,")
        self.assertNotIn("Twinkle, twinkle, little star", plan.scenes[0].video_prompt)
        self.assertIn("no generated text", plan.scenes[0].video_prompt)
        self.assertIn("no written words", plan.scenes[0].first_frame_prompt)

    def test_story_writer_outputs_pipeline_compatible_json(self):
        story = story_from_plan(self._plan())
        self.assertEqual(len(story["scenes"]), 3)
        first = story["scenes"][0]
        self.assertEqual(first["scene_num"], 1)
        self.assertIn("video_prompts", first)
        self.assertIn("first_frame_prompt", first)
        self.assertIn("cut", first)
        self.assertEqual(first["subtitle_text"], "Twinkle, twinkle, little star,")

    def test_storymem_script_matches_parent_storymem_schema(self):
        script = storymem_script_from_plan(self._plan())
        self.assertEqual(set(script), {"story_overview", "scenes"})
        self.assertEqual(len(script["scenes"]), 3)
        for index, scene in enumerate(script["scenes"], start=1):
            self.assertEqual(set(scene), {"scene_num", "video_prompts", "cut", "subtitle_text"})
            self.assertEqual(scene["scene_num"], index)
            self.assertEqual(len(scene["video_prompts"]), 1)
            self.assertEqual(len(scene["cut"]), 1)
            self.assertLess(len(scene["video_prompts"][0]), 900)
            self.assertNotIn("first_frame_prompt", scene)
            self.assertNotIn("agentic_metadata", scene)
            self.assertNotIn("audio_description", scene)
            self.assertNotIn("planned_start_seconds", scene)
        self.assertTrue(script["scenes"][0]["cut"][0])

    def test_default_storymem_dir_uses_in_repo_runtime(self):
        root = default_storymem_dir()
        self.assertTrue((root / "pipeline.py").exists())
        self.assertTrue((root / "wan").is_dir())
        self.assertTrue((root / "extract_keyframes.py").exists())

    def test_evaluator_flags_missing_media_and_feedback_targets_scenes(self):
        plan = self._plan()
        with tempfile.TemporaryDirectory() as tmp:
            report = evaluate_iteration(plan, Path(tmp), dry_run=False)
            self.assertFalse(report.passed)
            self.assertFalse(report.artifact_checks["clip_count"])
            revision = build_revision_plan(plan, report)
            self.assertEqual(revision.status, "needs_iteration")
            self.assertEqual(revision.target_scenes, [1, 2, 3])
            self.assertTrue(revision.regenerate_audio)

    def test_feedback_preserves_video_for_audio_only_failure(self):
        plan = self._plan()
        report = EvaluationReport(
            version="1.0",
            passed=False,
            artifact_checks={
                "storymem_compatible_plan": True,
                "clip_count": True,
                "final_video_exists": True,
                "has_video_stream": True,
                "has_audio_stream": True,
                "has_subtitles": True,
                "duration_match": True,
            },
            scene_reports=[],
            reviewer_reports=[
                ReviewerReport(
                    reviewer="WhisperXLyricTimingAgent",
                    passed=False,
                    failure_reasons=["wer_above_threshold"],
                    evidence={"lines": []},
                )
            ],
            failure_reasons=["wer_above_threshold"],
        )

        revision = build_revision_plan(plan, report)

        self.assertEqual(revision.target_scenes, [])
        self.assertEqual(revision.preserve_scenes, [1, 2, 3])
        self.assertTrue(revision.regenerate_audio)

    def test_feedback_ignores_non_mapping_model_suggestions(self):
        plan = self._plan()
        report = EvaluationReport(
            version="1.0",
            passed=False,
            artifact_checks={
                "storymem_compatible_plan": True,
                "clip_count": True,
                "final_video_exists": True,
                "has_video_stream": True,
                "has_audio_stream": True,
                "has_subtitles": True,
                "duration_match": True,
            },
            scene_reports=[],
            reviewer_reports=[
                ReviewerReport(
                    reviewer="ContinuityReviewAgent",
                    passed=False,
                    failure_reasons=["character_drift"],
                    evidence={
                        "target_scenes": [2],
                        "prompt_revisions": "met",
                        "first_frame_prompt_revisions": "met",
                        "subtitle_timing_adjustments": "met",
                        "mix_adjustments": "met",
                    },
                )
            ],
            regeneration_targets=[],
            failure_reasons=["character_drift"],
        )

        revision = build_revision_plan(plan, report)

        self.assertEqual(revision.target_scenes, [2])
        self.assertIn("2", revision.prompt_revisions)

    def test_cli_dry_run_writes_iteration_layout(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            rhyme = tmp_path / "rhyme.txt"
            rhyme.write_text("Twinkle star\nWonder far\nUp high\n", encoding="utf-8")
            out = tmp_path / "agentic"
            code = main(
                [
                    "dry-run",
                    "--rhyme-file",
                    str(rhyme),
                    "--output-dir",
                    str(out),
                    "--target-duration",
                    "12",
                    "--clip-count",
                    "3",
                ]
            )
            self.assertEqual(code, 0)
            iteration = out / "iterations" / "001"
            self.assertTrue((iteration / "production_plan.json").exists())
            self.assertTrue((iteration / "story.json").exists())
            self.assertTrue((iteration / "audio_plan.json").exists())
            self.assertTrue((iteration / "evaluation_report.json").exists())
            self.assertTrue((iteration / "revision_plan.json").exists())
            manifest = json.loads((out / "run_manifest.json").read_text(encoding="utf-8"))
            self.assertTrue(manifest["passed"])

    def test_topic_only_input_creates_fallback_lullaby_plan(self):
        plan = build_production_plan(
            NurseryRhymeInput(topic_or_name="moon bedtime lullaby", target_duration_seconds=16, clip_count=4)
        )
        self.assertEqual(plan.clip_count, 4)
        self.assertIn("moon bedtime lullaby", plan.lyric_segments[0].text)
        self.assertTrue(all(scene.subtitle_text for scene in plan.scenes))

    def test_prompt_planner_agent_uses_backend_decision_for_topic_only_plan(self):
        backend = MockAgentBackend(
            responses={"planner": self._structured_decision(["Line one from model", "Line two from model", "Line three from model"], character_label="cloud_child")}
        )
        plan = PromptPlannerAgent(backend).plan(NurseryRhymeInput(topic_or_name="any lullaby prompt"))
        self.assertEqual(plan.clip_count, 3)
        self.assertGreater(plan.lyric_segments[-1].end_seconds, 14.0)
        self.assertLessEqual(plan.lyric_segments[-1].end_seconds, 15.0)
        self.assertEqual([segment.text for segment in plan.lyric_segments], backend.responses["planner"]["lyrics"])
        self.assertEqual(plan.character_bank[0].label, "cloud_child")
        self.assertIn("Opening shot:", plan.scenes[0].description)
        self.assertIn("Camera", plan.scenes[0].description)
        self.assertEqual(plan.scenes[0].review_status, "approved")
        self.assertEqual(plan.scenes[0].selected_characters[0]["selection_rationale"], "fits lyric 1")
        self.assertIn("StoryMem keyframe memory", plan.scenes[0].video_prompt)
        self.assertLess(len(plan.scenes[0].video_prompt), 900)
        self.assertTrue(all(scene.cut for scene in plan.scenes))
        self.assertEqual(plan.music_prompt, "quiet celesta lullaby generated by backend")

    def test_planner_does_not_expand_unstructured_scene_semantics(self):
        backend = MockAgentBackend(
            responses={
                "planner": {
                    "lyrics": ["First line", "Second line", "Third line"],
                    "clip_count": 3,
                    "target_duration_seconds": 15,
                    "visual_bible": {},
                    "selected_characters": [{"label": "sleepy_child", "description": "same sleepy child", "selection_rationale": "fixture"}],
                    "scenes": [
                        {"description": "child looks at moon", "camera": "medium shot", "selected_characters": [{"label": "sleepy_child", "selection_rationale": "fixture"}]},
                        {"description": "moon shines over rooftops", "camera": "medium shot", "selected_characters": [{"label": "sleepy_child", "selection_rationale": "fixture"}]},
                        {"description": "child sleeps", "camera": "medium shot", "selected_characters": [{"label": "sleepy_child", "selection_rationale": "fixture"}]},
                    ],
                    "music_prompt": "soft lullaby",
                }
            }
        )

        planner = PromptPlannerAgent(backend)
        plan = planner.plan(NurseryRhymeInput(topic_or_name="moon lullaby"))

        issue_codes = {issue["code"] for issue in planner.last_validation_report["issues"]}
        self.assertIn("missing_structured_scene_field", issue_codes)
        self.assertEqual(plan.scenes[0].description, "Opening shot: child looks at moon")
        self.assertNotIn("tiny warm star lights", plan.scenes[0].description)
        self.assertFalse(validate_plan_semantics(plan)["passed"])

    def test_storymem_prompts_are_concise_and_scene_specific(self):
        plan = build_production_plan(
            NurseryRhymeInput(
                topic_or_name="Twinkle Twinkle Little Star",
                clip_count=5,
                target_duration_seconds=25,
            )
        )
        prompts = [scene.video_prompt for scene in plan.scenes]

        self.assertTrue(all(len(prompt) < 900 for prompt in prompts))
        self.assertLess(
            max(difflib.SequenceMatcher(None, prompts[index], prompts[index + 1]).ratio()
                for index in range(len(prompts) - 1)),
            0.7,
        )
        self.assertIn(f"Scene 1 of {plan.clip_count}", prompts[0])
        self.assertIn(f"Scene {plan.clip_count} of {plan.clip_count}", prompts[-1])

    def test_local_fallback_is_labeled_non_agentic_and_generic(self):
        plan = build_production_plan(
            NurseryRhymeInput(
                topic_or_name="Twinkle Twinkle Little Star",
                lyrics=(
                    "Twinkle, twinkle, little star\n"
                    "Little star above\n"
                    "How I wonder what you are\n"
                    "Up above the world so high\n"
                    "Like a diamond in the sky\n"
                ),
                clip_count=5,
                target_duration_seconds=25,
            )
        )

        descriptions = "\n".join(scene.description for scene in plan.scenes)

        self.assertTrue(all(scene.description.startswith("Opening shot:") for scene in plan.scenes))
        self.assertTrue(all("Camera" in scene.description for scene in plan.scenes))
        self.assertIn("Non-agentic dry-run scaffold only", descriptions)
        self.assertNotIn("tiny warm star lights", descriptions)
        self.assertNotIn("red schoolhouse", descriptions)

    def test_planner_revision_uses_structured_feedback_before_compilation(self):
        initial = self._structured_decision(["Rain, rain, go away", "Children want to play"], scene_suffix=" initial", character_label="rain_child")
        initial["scenes"][0]["safety_adaptation"] = ""
        revised = self._structured_decision(["Rain, rain, go away", "Children want to play"], scene_suffix=" revised", character_label="rain_child")
        backend = MockAgentBackend(responses={"planner": initial, "planner_revision_1": revised})

        planner = PromptPlannerAgent(backend, max_plan_revisions=1)
        plan = planner.plan(NurseryRhymeInput(topic_or_name="Rain Rain Go Away"))

        self.assertEqual(len(plan.scenes), 2)
        self.assertIn("revised", plan.scenes[1].description)
        self.assertTrue(validate_plan_semantics(plan)["passed"])
        self.assertEqual([step["kind"] for step in planner.agent_steps], ["planner_draft", "plan_review", "planner_revision", "plan_review"])

    def test_visible_bank_character_must_be_selected_for_scene(self):
        decision = self._structured_decision(["A fox greets an owl"], character_label="fox")
        decision["selected_characters"].append(
            {
                "label": "moon_owl",
                "description": "same round silver owl with blue wings",
                "selection_rationale": "the owl is greeted in the lyric",
            }
        )
        decision["scenes"][0]["subjects"] += "; moon owl waits beside the fox"
        plan = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0).plan(
            NurseryRhymeInput(topic_or_name="original fox and owl song")
        )

        report = validate_plan_semantics(plan, require_reviewer_approval=False)

        self.assertIn("visible_character_not_selected", {issue["code"] for issue in report["issues"]})

    def test_visual_bible_contains_used_cast_not_every_available_character(self):
        decision = self._structured_decision(["A fox crosses a hill"], character_label="fox")
        decision["selected_characters"].append(
            {
                "label": "unused_owl",
                "description": "same round silver owl with blue wings",
                "selection_rationale": "available supporting character",
            }
        )
        plan = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0).plan(
            NurseryRhymeInput(topic_or_name="original fox hill song")
        )

        recurring = {item["label"] for item in build_visual_bible(plan)["recurring_characters"]}

        self.assertIn("fox", recurring)
        self.assertNotIn("unused_owl", recurring)

    def test_planner_accepts_small_agent_authored_revision_patch(self):
        initial = self._structured_decision(["Copper kite", "Velvet hill"], character_label="fox")
        initial["scenes"][1]["setting"] = initial["scenes"][0]["setting"]
        initial["scenes"][1]["action"] = initial["scenes"][0]["action"]
        initial["scenes"][1]["camera"] = initial["scenes"][0]["camera"]
        patch = {
            "scene_revisions": [
                {"scene_num": 2, "field_to_change": "setting", "replacement_value": "a velvet hilltop with copper grass in the foreground and distant clouds"},
                {"scene_num": 2, "field_to_change": "action", "replacement_value": "the same fox catches the kite ribbon gently as it arcs over the hill"},
                {"scene_num": 2, "field_to_change": "camera", "replacement_value": "Camera tracks uphill beside the fox and settles on the kite"},
            ],
            "plan_updates": {},
        }
        backend = MockAgentBackend(responses={"planner": initial, "planner_revision_1": patch})

        planner = PromptPlannerAgent(backend, max_plan_revisions=1)
        plan = planner.plan(NurseryRhymeInput(topic_or_name="original copper kite journey"))

        self.assertTrue(validate_plan_semantics(plan)["passed"])
        self.assertIn("velvet hilltop", plan.scenes[1].setting)

    def test_unchanged_invalid_revision_is_reported_generically(self):
        invalid = self._structured_decision(["Copper kite", "Velvet hill"], character_label="fox")
        invalid["scenes"][1]["setting"] = invalid["scenes"][0]["setting"]
        invalid["scenes"][1]["action"] = invalid["scenes"][0]["action"]
        invalid["scenes"][1]["camera"] = invalid["scenes"][0]["camera"]
        backend = MockAgentBackend(responses={"planner": invalid, "planner_revision_1": invalid})

        planner = PromptPlannerAgent(backend, max_plan_revisions=1)
        planner.plan(NurseryRhymeInput(topic_or_name="an original copper kite journey"))

        second_codes = {
            issue["code"] for issue in planner.plan_attempts[1]["deterministic_report"]["issues"]
        }
        self.assertIn("revision_made_no_changes", second_codes)
        self.assertIn("repeated_scene_staging", second_codes)

    def test_unsafe_motion_feedback_drives_general_agentic_revision(self):
        initial = self._structured_decision(["High branch line", "Safe landing line"], character_label="guide")
        initial["scenes"][0]["action"] = "the small guide falls from a high platform"
        initial["scenes"][0]["safety_adaptation"] = "no text, no dialogue, no inset frame, no scary imagery"
        revised = self._structured_decision(["High branch line", "Safe landing line"], scene_suffix=" revised", character_label="guide")
        revised["scenes"][0]["action"] = "the small guide gently lowers on a supported cushion path"
        revised["scenes"][0]["safety_adaptation"] = "supported safely, no dialogue, no generated text, no inset frame, no scary imagery"
        backend = MockAgentBackend(responses={"planner": initial, "planner_revision_1": revised})

        planner = PromptPlannerAgent(backend, max_plan_revisions=1)
        plan = planner.plan(NurseryRhymeInput(topic_or_name="generic safety lullaby"))

        first_attempt_issues = planner.plan_attempts[0]["deterministic_report"]["issues"]
        unsafe_issue = next(issue for issue in first_attempt_issues if issue["code"] == "unsafe_visual_action")
        self.assertIn("evidence", unsafe_issue)
        self.assertTrue(validate_plan_semantics(plan)["passed"])
        self.assertIn("supported cushion path", plan.scenes[0].description)
        self.assertNotIn("falls", plan.scenes[0].description.lower())

    def test_critic_cannot_override_deterministic_safety_failure(self):
        decision = self._structured_decision(["A dangerous line"], character_label="baby")
        decision["scenes"][0]["action"] = "the baby falls from a high branch"
        plan = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0).plan(
            NurseryRhymeInput(topic_or_name="safety test")
        )
        deterministic = validate_plan_semantics(plan, require_reviewer_approval=False)
        critic = PlanCriticAgent(MockAgentBackend(responses={"plan_critic": {"passed": True, "issues": []}}))

        report = critic.review(plan, deterministic)

        self.assertFalse(report["passed"])
        self.assertIn("unsafe_visual_action", {issue["code"] for issue in report["issues"]})

    def test_critic_rejection_without_issues_fails_closed(self):
        decision = self._structured_decision(["A quiet copper kite"])
        plan = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0).plan(
            NurseryRhymeInput(topic_or_name="original copper kite lullaby")
        )
        critic = PlanCriticAgent(
            MockAgentBackend(responses={"plan_critic": {"passed": False, "issues": [], "scores": {}}})
        )

        report = critic.review(plan, validate_plan_semantics(plan, require_reviewer_approval=False))

        self.assertFalse(report["passed"])
        self.assertEqual(report["issues"][0]["code"], "critic_rejected_without_issues")

    def test_critic_normalizes_actionable_generic_review(self):
        decision = self._structured_decision(["A fox crosses a velvet hill"])
        plan = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0).plan(
            NurseryRhymeInput(topic_or_name="original velvet hill lullaby")
        )
        critic = PlanCriticAgent(
            MockAgentBackend(
                responses={
                    "plan_critic": {
                        "passed": False,
                        "issues": [{
                            "code": "Camera Conflict",
                            "scene_num": "1",
                            "reason": "shot size contradicts the camera move",
                            "field": "camera",
                            "evidence": {
                                "observed": "Camera makes a slow planned move 1",
                                "expected": "one coherent camera direction",
                                "source": "review_contract.prompt_generatability",
                            },
                            "suggested_change": "use one eye-level tracking direction",
                            "replacement_value": "Camera tracks gently at child-eye level",
                        }],
                        "scores": {"prompt_generatability": 1.4, "lyric_alignment": "0.8", "bad": "unknown"},
                        "revision_notes": ["  Resolve the camera field.  "],
                    }
                }
            )
        )

        report = critic.review(plan, validate_plan_semantics(plan, require_reviewer_approval=False))

        self.assertEqual(report["issues"][0]["code"], "camera_conflict")
        self.assertEqual(report["issues"][0]["scene_num"], 1)
        self.assertEqual(
            report["targeted_revision"]["scene_revisions"][0]["replacement_value"],
            "Camera tracks gently at child-eye level",
        )
        self.assertEqual(report["scores"], {"prompt_generatability": 1.0, "lyric_alignment": 0.8})
        self.assertEqual(report["revision_notes"], ["Resolve the camera field"])

    def test_ungrounded_critic_claim_is_advisory_not_blocking(self):
        decision = self._structured_decision(["A lamb looks up with curiosity"])
        plan = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0).plan(
            NurseryRhymeInput(topic_or_name="original curious lamb lullaby")
        )
        critic = PlanCriticAgent(
            MockAgentBackend(responses={"plan_critic": {
                "passed": False,
                "issues": [{
                    "code": "visual_continuity",
                    "scene_num": 1,
                    "message": "looking upward is inconsistent",
                    "field": "action",
                    "evidence": "the lamb looks upward",
                    "suggested_change": "make the lamb look elsewhere",
                }],
            }})
        )

        report = critic.review(plan, validate_plan_semantics(plan, require_reviewer_approval=False))

        self.assertTrue(report["passed"])
        self.assertEqual(report["issues"], [])
        self.assertEqual(report["warnings"][0]["code"], "visual_continuity")

    def test_critic_rejects_identical_observed_and_expected_evidence(self):
        decision = self._structured_decision(["A mouse circles a brass clock"])
        plan = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0).plan(
            NurseryRhymeInput(topic_or_name="original brass clock lullaby")
        )
        critic = PlanCriticAgent(MockAgentBackend(responses={"plan_critic": {
            "passed": False,
            "issues": [{
                "code": "visual_continuity",
                "scene_num": 1,
                "message": "character metadata conflicts",
                "field": "selected_characters",
                "evidence": {
                    "observed": "guide",
                    "expected": "guide",
                    "source": "visual_bible",
                },
                "suggested_change": "keep guide unchanged",
            }],
        }}))

        report = critic.review(plan, validate_plan_semantics(plan, require_reviewer_approval=False))

        self.assertTrue(report["passed"])
        self.assertEqual(report["issues"], [])

    def test_semantic_critic_hygiene_opinion_is_advisory(self):
        decision = self._structured_decision(["A child greets a lamb"])
        plan = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0).plan(
            NurseryRhymeInput(topic_or_name="original lamb greeting")
        )
        critic = PlanCriticAgent(MockAgentBackend(responses={"plan_critic": {
            "passed": False,
            "issues": [{
                "code": "prompt_hygiene",
                "scene_num": 1,
                "message": "the broad goal could be more detailed",
                "field": "scene_goal",
                "evidence": {
                    "observed": "communicate lyric 1",
                    "expected": "describe every gesture",
                    "source": "review_contract.prompt_hygiene",
                },
                "suggested_change": "expand the goal",
            }],
        }}))

        report = critic.review(plan, validate_plan_semantics(plan, require_reviewer_approval=False))

        self.assertTrue(report["passed"])
        self.assertEqual(report["issues"], [])
        self.assertEqual(report["warnings"][0]["code"], "prompt_hygiene")

    def test_semantic_reviewer_applies_targeted_field_patch_without_full_replan(self):
        decision = self._structured_decision(["The fox waves to the moon"], character_label="fox")
        decision["scenes"][0]["action"] = "the fox sits without reacting"

        class OneShotSemanticReviewer:
            def __init__(self):
                self.calls = 0

            def generate_json(self, prompt, schema, context):
                self.calls += 1
                if self.calls > 1:
                    return {"passed": True, "issues": [], "scores": {}, "revision_notes": []}
                return {
                    "passed": False,
                    "issues": [{
                        "code": "lyric_alignment",
                        "scene_num": 1,
                        "field": "action",
                        "message": "the fox never performs the lyric's greeting",
                        "evidence": {
                            "observed": "the fox sits without reacting",
                            "expected": "the fox waves to the moon",
                            "source": "review_contract.lyric_alignment",
                        },
                        "suggested_change": "replace only the action with a visible wave",
                        "replacement_value": "the fox smiles and waves one paw toward the moon",
                    }],
                    "scores": {"lyric_alignment": 0.4},
                    "revision_notes": ["Target scene 1 action only"],
                }

        reviewer_backend = OneShotSemanticReviewer()
        planner = PromptPlannerAgent(
            MockAgentBackend(responses={"planner": decision}),
            critic=PlanCriticAgent(reviewer_backend),
            max_plan_revisions=2,
        )

        plan = planner.plan(NurseryRhymeInput(topic_or_name="original moon greeting"))

        self.assertTrue(validate_plan_semantics(plan)["passed"])
        self.assertEqual(plan.scenes[0].action, "the fox smiles and waves one paw toward the moon")
        self.assertEqual(reviewer_backend.calls, 2)
        self.assertTrue(any(step.get("source") == "PlanCriticAgent" for step in planner.agent_steps))

    def test_consecutive_identical_staging_requires_revision(self):
        decision = self._structured_decision(["Line one", "Line two"])
        for field in ("setting", "action", "camera"):
            decision["scenes"][1][field] = decision["scenes"][0][field]
        planner = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0)

        planner.plan(NurseryRhymeInput(topic_or_name="repetition test"))

        codes = {issue["code"] for issue in planner.last_validation_report["issues"]}
        self.assertIn("repeated_scene_staging", codes)

    def test_flat_camera_coverage_requires_directorial_revision(self):
        decision = self._structured_decision(["Set up", "Build", "React", "Pay off"])
        for scene in decision["scenes"]:
            scene["camera"] = "Camera holds a static medium shot"
        planner = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0)

        planner.plan(NurseryRhymeInput(topic_or_name="original playful shape parade"))

        codes = {issue["code"] for issue in planner.last_validation_report["issues"]}
        self.assertIn("repeated_camera_coverage", codes)

    def test_overcrowded_five_second_shot_requires_focus(self):
        decision = self._structured_decision(["Friends gather for a game"])
        decision["selected_characters"] = [
            {
                "label": f"friend_{index}",
                "description": f"same colorful rounded friend {index}",
                "selection_rationale": "joins the game",
            }
            for index in range(1, 5)
        ]
        decision["scenes"][0]["selected_characters"] = [
            {"label": f"friend_{index}", "selection_rationale": "joins the game"}
            for index in range(1, 5)
        ]
        planner = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0)

        planner.plan(NurseryRhymeInput(topic_or_name="original playground game"))

        codes = {issue["code"] for issue in planner.last_validation_report["issues"]}
        self.assertIn("overcrowded_five_second_shot", codes)

    def test_compiled_prompt_uses_natural_character_text_and_authoritative_camera(self):
        decision = self._structured_decision(["Line one"], character_label="rain_child")
        decision["scenes"][0]["subjects"] = [
            {"label": "rain_child", "selection_rationale": "fits the scene"},
            "beside a rainy window",
        ]
        decision["scenes"][0]["camera"] = "Camera holds a steady eye-level medium shot"
        plan = PromptPlannerAgent(MockAgentBackend(responses={"planner": decision}), max_plan_revisions=0).plan(
            NurseryRhymeInput(topic_or_name="camera test")
        )

        prompt = plan.scenes[0].video_prompt
        self.assertIn("featuring same rounded rain_child", prompt)
        self.assertNotIn("{'label':", prompt)
        self.assertNotIn("wide establishing shot", prompt)

    def test_natural_falling_rain_is_not_unsafe_motion(self):
        plan = build_production_plan(
            NurseryRhymeInput(lyrics="Rain taps softly\nDream now\n", target_duration_seconds=10, clip_count=2)
        )
        plan.scenes[0].setting = "a garden window with raindrops falling in the background"
        plan.scenes[0].description = (
            "Opening shot: a garden window with raindrops falling in the background. "
            "same toddler-safe pajama child in every scene watches calmly. "
            "Camera holds still. soft style. no generated text, no dialogue, no inset frame, no scary imagery."
        )
        plan.scenes[0].video_prompt = (
            "Scene 1, toddler-safe lullaby animation: raindrops falling outside a window. "
            "No dialogue or background music, no generated text, no picture-in-picture, no inset frame, no scary elements."
        )

        self.assertTrue(validate_plan_semantics(plan)["passed"])

    def test_model_review_normalizer_accepts_scalar_scores(self):
        report = _normalize_model_report(
            "VisualSafetyReviewAgent",
            {
                "passed": True,
                "scores": 1.0,
                "failure_reasons": [],
                "evidence": {"sampled_frames_checked": True},
            },
        )

        self.assertTrue(report.passed)
        self.assertEqual(report.scores["overall"], 1.0)

    def test_character_db_profiles_are_preserved_without_prompt_injection(self):
        with tempfile.TemporaryDirectory() as tmp:
            db = Path(tmp) / "characters.json"
            db.write_text(
                json.dumps(
                    {
                        "characters": [
                            {
                                "id": "moon_bear",
                                "visual_description": "same plush moon bear with silver cap",
                                "continuity_constraints": ["silver cap stays visible"],
                                "negative_constraints": ["no text on cap"],
                                "reference_image_paths": ["refs/moon_bear.png"],
                            }
                        ]
                    }
                ),
                encoding="utf-8",
            )
            plan = build_production_plan(
                NurseryRhymeInput(
                    lyrics="Hush now\nDream now\n",
                    target_duration_seconds=8,
                    clip_count=2,
                    character_db_path=str(db),
                )
            )
            self.assertEqual(plan.character_bank[0].label, "moon_bear")
            self.assertNotIn("moon_bear", plan.scenes[0].video_prompt)
            self.assertEqual(plan.character_bank[0].reference_image_paths, ["refs/moon_bear.png"])

    def test_character_bank_profiles_are_selected_into_scene_descriptions(self):
        with tempfile.TemporaryDirectory() as tmp:
            bank = Path(tmp) / "characters.json"
            bank.write_text(
                json.dumps(
                    {
                        "characters": [
                            {
                                "id": "rain_child",
                                "role": "child",
                                "description": "same child in yellow raincoat with red boots",
                                "visual_anchors": ["yellow raincoat", "red boots"],
                                "allowed_variants": ["hood up", "hood down"],
                                "negative_constraints": ["no text on coat"],
                            }
                        ]
                    }
                ),
                encoding="utf-8",
            )

            plan = build_production_plan(
                NurseryRhymeInput(
                    topic_or_name="Rain Rain Go Away",
                    lyrics="Rain, rain, go away\nCome again another day\n",
                    clip_count=2,
                    character_bank_path=str(bank),
                )
            )

            self.assertEqual(plan.character_bank[0].role, "child")
            self.assertIn("same child in yellow raincoat with red boots", plan.scenes[0].description)
            self.assertIn("yellow raincoat", plan.scenes[1].description)
            self.assertTrue(validate_plan_semantics(plan)["passed"])

    def test_generate_blocks_when_agentic_plan_fails_structural_validation(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            planner_script = tmp_path / "incomplete_planner.py"
            planner_script.write_text(
                "import json, sys\n"
                "json.load(sys.stdin)\n"
                "print(json.dumps({"
                "'lyrics':['Line one','Line two'],"
                "'clip_count':2,"
                "'target_duration_seconds':10,"
                "'visual_bible':{},"
                "'selected_characters':[{'label':'guide','description':'same guide','selection_rationale':'fixture'}],"
                "'scenes':[{'description':'Opening shot: incomplete scene','camera':'slow push'}],"
                "'music_prompt':'soft lullaby'"
                "}))\n",
                encoding="utf-8",
            )
            with self.assertRaises(ValueError):
                run_workflow(
                    topic_or_name="Rock-a-bye Baby",
                    output_dir=tmp_path / "blocked",
                    mode="generate",
                    planner_backend="command",
                    planner_command=f"{sys.executable} {planner_script}",
                    generate_audio=False,
                    execute_video=False,
                    max_plan_revisions=0,
                )


    def test_whisperx_alignment_flags_timing_drift(self):
        result = analyze_whisperx_alignment(
            ["Hush now"],
            [(2.0, 3.0)],
            [{"word": "Hush", "start": 0.8, "end": 1.0}, {"word": "now", "start": 1.05, "end": 1.2}],
        )
        self.assertFalse(result["passed"])
        self.assertIn("line_1_starts_before_scene", result["failure_reasons"])

    def test_full_song_timing_failure_triggers_scene_mix_fallback(self):
        from storymem_agentic.orchestrator import _needs_scene_lyrics_audio_fallback

        self.assertTrue(
            _needs_scene_lyrics_audio_fallback(
                {
                    "passed": False,
                    "failure_reasons": [
                        "line_1_missing_words",
                        "line_2_ends_after_scene",
                    ],
                }
            )
        )
        self.assertTrue(
            _needs_scene_lyrics_audio_fallback(
                {
                    "passed": False,
                    "failure_reasons": ["wer_above_threshold"],
                }
            )
        )
        self.assertFalse(_needs_scene_lyrics_audio_fallback({"passed": True, "failure_reasons": []}))

    def test_cli_plan_accepts_topic_and_writes_reviewer_reports(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "topic_plan"
            code = main(
                [
                    "plan",
                    "--topic",
                    "moon bedtime lullaby",
                    "--output-dir",
                    str(out),
                    "--target-duration",
                    "12",
                    "--clip-count",
                    "3",
                ]
            )
            self.assertEqual(code, 0)
            iteration = out / "iterations" / "001"
            self.assertTrue((iteration / "storymem_commands.json").exists())
            self.assertTrue((iteration / "review_reports" / "ArtifactReviewAgent.json").exists())
            plan = json.loads((iteration / "production_plan.json").read_text(encoding="utf-8"))
            self.assertEqual(plan["rhyme"]["topic_or_name"], "moon bedtime lullaby")

    def test_command_review_backend_requires_vlm_command(self):
        report = evaluate_iteration(
            self._plan(),
            Path("/tmp/nonexistent-agentic-review"),
            dry_run=True,
            review_backend="command",
        )

        failed_reviewers = {item.reviewer: item.failure_reasons for item in report.reviewer_reports if not item.passed}
        self.assertIn("VisualSafetyReviewAgent", failed_reviewers)
        self.assertIn("missing_vlm_command", failed_reviewers["VisualSafetyReviewAgent"])

    def test_command_review_backend_uses_model_suggestions_in_revision(self):
        plan = self._plan()
        report = EvaluationReport(
            version="1.0",
            passed=False,
            artifact_checks={
                "storymem_compatible_plan": True,
                "clip_count": True,
                "final_video_exists": True,
                "has_video_stream": True,
                "has_audio_stream": True,
                "has_subtitles": True,
                "duration_match": True,
            },
            scene_reports=[],
            reviewer_reports=[
                ReviewerReport(
                    reviewer="StoryAlignmentReviewAgent",
                    passed=False,
                    failure_reasons=["scene_2_lyric_mismatch"],
                    evidence={
                        "target_scenes": [2],
                        "prompt_revisions": {"2": "Show the child wondering at the star more clearly."},
                    },
                ),
                ReviewerReport(
                    reviewer="AudioReviewAgent",
                    passed=False,
                    failure_reasons=["music_too_harsh"],
                    evidence={"audio_prompt_revision": "Make the arrangement softer and slower."},
                ),
            ],
            failure_reasons=["scene_2_lyric_mismatch", "music_too_harsh"],
        )

        revision = build_revision_plan(plan, report)

        self.assertEqual(revision.target_scenes, [2])
        self.assertEqual(revision.preserve_scenes, [1, 3])
        self.assertIn("wondering at the star", revision.prompt_revisions["2"])
        self.assertIn("softer and slower", revision.audio_prompt_revision)

    def test_cli_optional_parameters_modify_planner_input_and_are_persisted(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "overrides"
            code = main(
                [
                    "plan",
                    "--topic",
                    "rainy nap lullaby",
                    "--output-dir",
                    str(out),
                    "--target-audience",
                    "preschoolers",
                    "--visual-style",
                    "soft watercolor bedtime animation",
                    "--audio-style",
                    "hummed lullaby with quiet piano",
                    "--target-duration",
                    "18",
                    "--clip-count",
                    "3",
                ]
            )
            self.assertEqual(code, 0)
            user_input = json.loads((out / "nursery_rhyme_input.json").read_text(encoding="utf-8"))
            self.assertEqual(user_input["target_audience"], "preschoolers")
            self.assertEqual(user_input["visual_style"], "soft watercolor bedtime animation")
            self.assertEqual(user_input["audio_style"], "hummed lullaby with quiet piano")
            planner_output = json.loads((out / "planner_agent_output.json").read_text(encoding="utf-8"))
            self.assertTrue(planner_output["used_fallback"])
            plan = json.loads((out / "iterations" / "001" / "production_plan.json").read_text(encoding="utf-8"))
            self.assertIn("soft watercolor bedtime animation", plan["scenes"][0]["video_prompt"])
            self.assertIn("hummed lullaby with quiet piano", plan["music_prompt"])

    def test_cli_direct_lyrics_are_preserved_exactly(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "direct_lyrics"
            lyrics = "Custom hush line\nCustom dream line\n"
            code = main(
                [
                    "plan",
                    "--topic",
                    "custom lullaby",
                    "--lyrics",
                    lyrics,
                    "--output-dir",
                    str(out),
                ]
            )
            self.assertEqual(code, 0)
            plan = json.loads((out / "iterations" / "001" / "production_plan.json").read_text(encoding="utf-8"))
            self.assertEqual([item["text"] for item in plan["lyric_segments"]], ["Custom hush line", "Custom dream line"])

    def test_command_planner_output_is_normalized_and_persisted(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            planner_script = tmp_path / "planner_backend.py"
            decision = self._structured_decision(["Backend line one", "Backend line two"], character_label="night_light")
            decision["music_prompt"] = "backend music prompt"
            planner_script.write_text(
                "import json, sys\n"
                "json.load(sys.stdin)\n"
                f"print(json.dumps({decision!r}))\n",
                encoding="utf-8",
            )
            out = tmp_path / "command_plan"
            code = main(
                [
                    "plan",
                    "--topic",
                    "any lullaby",
                    "--output-dir",
                    str(out),
                    "--planner-backend",
                    "command",
                    "--planner-command",
                    f"{sys.executable} {planner_script}",
                ]
            )
            self.assertEqual(code, 0)
            planner_output = json.loads((out / "planner_agent_output.json").read_text(encoding="utf-8"))
            self.assertFalse(planner_output["used_fallback"])
            self.assertEqual(planner_output["response"]["lyrics"][0], "Backend line one")
            plan = json.loads((out / "iterations" / "001" / "production_plan.json").read_text(encoding="utf-8"))
            self.assertEqual(plan["character_bank"][0]["label"], "night_light")
            self.assertIn("Opening shot:", plan["scenes"][0]["description"])
            self.assertIn("Camera", plan["scenes"][0]["description"])
            self.assertEqual(plan["scenes"][0]["review_status"], "approved")
            self.assertTrue((out / "planner_draft_01.json").exists())
            self.assertTrue((out / "plan_review_01.json").exists())

    def test_command_planner_invalid_json_blocks_generation(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            planner_script = tmp_path / "bad_planner_backend.py"
            planner_script.write_text(
                "import json, sys\n"
                "json.load(sys.stdin)\n"
                "print(json.dumps({'type':'object','properties':{'lyrics':{'type':'array'}}}))\n",
                encoding="utf-8",
            )
            out = tmp_path / "bad_command_plan"
            with self.assertRaises(ValueError):
                run_workflow(
                    topic_or_name="any lullaby",
                    output_dir=out,
                    mode="generate",
                    planner_backend="command",
                    planner_command=f"{sys.executable} {planner_script}",
                    generate_audio=False,
                    execute_video=False,
                )
            planner_output = json.loads((out / "planner_agent_output.json").read_text(encoding="utf-8"))
            self.assertFalse(planner_output["used_fallback"])
            self.assertIsNone(planner_output["fallback_policy"])
            self.assertIn("planner decision did not provide lyrics", planner_output["error"])
            self.assertFalse((out / "iterations" / "001" / "production_plan.json").exists())

    def test_iterate_applies_revision_plan_to_next_iteration_json(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "revision_loop"
            result = run_workflow(
                topic_or_name="moon bedtime lullaby",
                output_dir=out,
                mode="iterate",
                target_duration=12,
                clip_count=3,
                max_iterations=2,
                audio_aligner="none",
                generate_audio=False,
            )
            self.assertFalse(result["passed"])
            first = json.loads((out / "iterations" / "001" / "production_plan.json").read_text(encoding="utf-8"))
            second = json.loads((out / "iterations" / "002" / "production_plan.json").read_text(encoding="utf-8"))
            self.assertNotEqual(first["scenes"][0]["video_prompt"], second["scenes"][0]["video_prompt"])
            self.assertIn("Revision guidance", second["scenes"][0]["video_prompt"])
            self.assertTrue((out / "iterations" / "001" / "revision_plan.json").exists())

    def test_partial_whisperx_timing_revision_does_not_break_monotonic_plan(self):
        plan = build_production_plan(
            NurseryRhymeInput(
                topic_or_name="twinkle",
                lyrics="\n".join([f"Line {index}" for index in range(1, 7)]),
                clip_count=6,
            )
        )
        revision = RevisionPlan(
            version="1.0",
            status="needs_iteration",
            lyric_timing_adjustments={
                "1": {"observed_start_seconds": 0.2, "observed_end_seconds": 3.4},
                "2": {"observed_start_seconds": 4.5, "observed_end_seconds": 7.7},
                "3": {"observed_start_seconds": 8.8, "observed_end_seconds": 11.8},
                "4": {"observed_start_seconds": 13.0, "observed_end_seconds": 20.4},
                "5": {"observed_start_seconds": None, "observed_end_seconds": None},
                "6": {"observed_start_seconds": None, "observed_end_seconds": None},
            },
        )

        revised = apply_revision_plan(plan, revision)

        self.assertEqual(
            [(segment.start_seconds, segment.end_seconds) for segment in revised.lyric_segments],
            [(segment.start_seconds, segment.end_seconds) for segment in plan.lyric_segments],
        )

    def test_storymem_commands_split_first_shot_story_from_full_story(self):
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "commands"
            code = main(
                [
                    "generate",
                    "--topic",
                    "moon bedtime lullaby",
                    "--output-dir",
                    str(out),
                    "--storymem-dir",
                    "/tmp/storymem",
                    "--t2v-model-path",
                    "/tmp/t2v",
                    "--i2v-model-path",
                    "/tmp/i2v",
                    "--lora-weight-path",
                    "/tmp/lora",
                    "--no-execute-video",
                    "--no-generate-audio",
                    "--audio-aligner",
                    "none",
                ]
            )
            self.assertEqual(code, 0)
            iteration = out / "iterations" / "001"
            commands = json.loads((iteration / "storymem_commands.json").read_text(encoding="utf-8"))["commands"]
            self.assertTrue(any("story_t2v_first_shot.json" in value for value in commands[0]))
            self.assertTrue(any(value.endswith("storymem_story.json") for value in commands[1]))
            self.assertIn("--t2v_first_shot", commands[0])
            self.assertNotIn("--mi2v", commands[0])
            self.assertIn("--mi2v", commands[1])
            self.assertEqual(commands[0][commands[0].index("--seed") + 1], "0")
            self.assertEqual(commands[1][commands[1].index("--seed") + 1], "0")
            first_story = json.loads((iteration / "story_t2v_first_shot.json").read_text(encoding="utf-8"))
            storymem_story = json.loads((iteration / "storymem_story.json").read_text(encoding="utf-8"))
            full_story = json.loads((iteration / "story.json").read_text(encoding="utf-8"))
            self.assertEqual(len(first_story["scenes"]), 1)
            self.assertGreater(len(storymem_story["scenes"]), 1)
            self.assertGreater(len(full_story["scenes"]), 1)
            self.assertNotIn("first_frame_prompt", storymem_story["scenes"][0])
            self.assertIn("first_frame_prompt", full_story["scenes"][0])

    def test_first_shot_keyframe_fallback_uses_last_frame(self) -> None:
        from storymem_agentic.orchestrator import ensure_first_shot_memory_keyframe

        with tempfile.TemporaryDirectory() as tmp:
            generated = Path(tmp)
            last_frame = generated / "last_frame.jpg"
            last_frame.write_bytes(b"fake image bytes")

            fallback = ensure_first_shot_memory_keyframe(generated)

            self.assertEqual(fallback, generated / "01_01_keyframe0.jpg")
            self.assertEqual(fallback.read_bytes(), b"fake image bytes")

    def test_first_shot_keyframe_fallback_preserves_existing_keyframe(self) -> None:
        from storymem_agentic.orchestrator import ensure_first_shot_memory_keyframe

        with tempfile.TemporaryDirectory() as tmp:
            generated = Path(tmp)
            (generated / "01_01_keyframe0.jpg").write_bytes(b"existing")
            (generated / "last_frame.jpg").write_bytes(b"last")

            fallback = ensure_first_shot_memory_keyframe(generated)

            self.assertIsNone(fallback)
            self.assertEqual((generated / "01_01_keyframe0.jpg").read_bytes(), b"existing")

    def test_storymem_commands_resolve_paths_before_cwd_change(self) -> None:
        from storymem_agentic.orchestrator import build_storymem_commands

        commands = build_storymem_commands(
            story_json=Path("relative/out/iterations/001/story.json"),
            first_shot_story_json=Path("relative/out/iterations/001/story_t2v_first_shot.json"),
            output_dir=Path("relative/out/iterations/001/generated"),
            storymem_dir="/tmp/storymem",
            t2v_model_path=Path("models/t2v"),
            i2v_model_path=Path("models/i2v"),
            lora_weight_path=Path("models/lora"),
            nproc_per_node=2,
            t5_cpu=True,
        )

        first = commands[0]
        self.assertTrue(Path(first[first.index("--story_script_path") + 1]).is_absolute())
        self.assertTrue(Path(first[first.index("--output_dir") + 1]).is_absolute())
        self.assertTrue(Path(first[first.index("--t2v_model_path") + 1]).is_absolute())
        self.assertIn("--t5_cpu", first)

    def test_storymem_commands_default_to_in_repo_pipeline_runtime(self) -> None:
        from storymem_agentic.orchestrator import build_storymem_commands

        commands = build_storymem_commands(
            story_json=Path("relative/out/iterations/001/storymem_story.json"),
            first_shot_story_json=Path("relative/out/iterations/001/story_t2v_first_shot.json"),
            output_dir=Path("relative/out/iterations/001/generated"),
            storymem_dir=None,
            t2v_model_path=Path("models/t2v"),
            i2v_model_path=Path("models/i2v"),
            lora_weight_path=Path("models/lora"),
            nproc_per_node=4,
        )

        self.assertEqual(commands[0][commands[0].index("pipeline.py")], "pipeline.py")
        self.assertTrue((default_storymem_dir() / "pipeline.py").exists())

    def test_storymem_commands_expose_speed_options(self) -> None:
        from storymem_agentic.orchestrator import build_storymem_commands

        commands = build_storymem_commands(
            story_json=Path("relative/out/iterations/001/story.json"),
            first_shot_story_json=Path("relative/out/iterations/001/story_t2v_first_shot.json"),
            output_dir=Path("relative/out/iterations/001/generated"),
            storymem_dir="/tmp/storymem",
            t2v_model_path=Path("models/t2v"),
            i2v_model_path=Path("models/i2v"),
            lora_weight_path=Path("models/lora"),
            nproc_per_node=8,
            sample_steps=20,
            frame_num=41,
            keyframe_mode="simple",
            seed=123,
        )

        first = commands[0]
        second = commands[1]
        self.assertNotIn("--offload_model", first)
        self.assertNotIn("--offload_model", second)
        self.assertEqual(first[first.index("--sample_steps") + 1], "20")
        self.assertEqual(second[second.index("--frame_num") + 1], "41")
        self.assertEqual(first[first.index("--keyframe_mode") + 1], "simple")
        self.assertEqual(first[first.index("--seed") + 1], "123")
        self.assertEqual(second[second.index("--seed") + 1], "123")

    def test_resume_reuses_completed_iteration_reports(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "resume"
            result = run_workflow(
                topic_or_name="moon bedtime lullaby",
                output_dir=out,
                mode="iterate",
                target_duration=10,
                clip_count=2,
                max_iterations=1,
                generate_audio=False,
                execute_video=False,
            )
            self.assertFalse(result["passed"])
            report_path = out / "iterations" / "001" / "evaluation_report.json"
            original_report = json.loads(report_path.read_text(encoding="utf-8"))
            original_report["failure_reasons"] = ["cached_marker"]
            report_path.write_text(json.dumps(original_report, indent=2) + "\n", encoding="utf-8")

            resumed = run_workflow(
                topic_or_name="moon bedtime lullaby",
                output_dir=out,
                mode="iterate",
                target_duration=10,
                clip_count=2,
                max_iterations=1,
                generate_audio=False,
                execute_video=False,
            )

            self.assertFalse(resumed["passed"])
            self.assertEqual(
                json.loads(report_path.read_text(encoding="utf-8"))["failure_reasons"],
                ["cached_marker"],
            )

    def test_storymem_continuation_command_uses_mi2v_only(self) -> None:
        from storymem_agentic.orchestrator import build_storymem_continuation_command

        command = build_storymem_continuation_command(
            story_json=Path("relative/out/iterations/002/story_from_scene_02.json"),
            output_dir=Path("relative/out/iterations/002/generated"),
            storymem_dir="/tmp/storymem",
            t2v_model_path=Path("models/t2v"),
            i2v_model_path=Path("models/i2v"),
            lora_weight_path=Path("models/lora"),
            nproc_per_node=4,
            seed=456,
        )

        self.assertIn("--mi2v", command)
        self.assertNotIn("--t2v_first_shot", command)
        self.assertEqual(command[command.index("--seed") + 1], "456")
        self.assertTrue(Path(command[command.index("--story_script_path") + 1]).is_absolute())


if __name__ == "__main__":
    unittest.main()
